pub const UNICODE_VOID: &str = " ";
pub const UNICODE_BODY: &str = "┃";
pub const UNICODE_HALF_BODY_BOTTOM: &str = "╻";
pub const UNICODE_HALF_BODY_TOP: &str = "╹";
pub const UNICODE_WICK: &str = "│";
pub const UNICODE_TOP: &str = "╽";
pub const UNICODE_BOTTOM: &str = "╿";
pub const UNICODE_UPPER_WICK: &str = "╷";
pub const UNICODE_LOWER_WICK: &str = "╵";
