const UNICODE_VOID: char = ' ';
const UNICODE_BODY: char = '┃';
const UNICODE_HALF_BODY_BOTTOM: char = '╻';
const UNICODE_HALF_BODY_TOP: char = '╹';
const UNICODE_WICK: char = '│';
const UNICODE_TOP: char = '╽';
const UNICODE_BOTTOM: char = '╿';
const UNICODE_UPPER_WICK: char = '╷';
const UNICODE_LOWER_WICK: char = '╵';
